#!/usr/bin/env bash
# --- [ NVIDIA DRIVER & DKMS ENGINE ] ---

set -euo pipefail

# --- [ HARDWARE DETECTION & DKMS CHECK ] ---
detect_nvidia_gpu() {
    probe_gpu_hardware
    if [ "${HAS_NVIDIA}" = "false" ]; then
        echo "NONE"
        return 0
    fi

    local pci_devs
    pci_devs=$(lspci -nn 2>/dev/null | grep -iE 'vga|3d|display' | grep -i 'nvidia' || true)

    if echo "${pci_devs}" | grep -qE '\[10de:(1b[0-9a-f]|1c[0-9a-f]|1d[0-9a-f])\]'; then
        echo "PASCAL"
    else
        echo "MODERN"
    fi
}

ensure_dkms_installed_interactive() {
    probe_gpu_hardware
    [ "${HAS_NVIDIA}" = "true" ] || return 0

    if command -v dkms >/dev/null 2>&1; then
        return 0
    fi

    echo ""
    log_warn "DKMS utility is not installed on this system."
    echo "DKMS is required to automatically rebuild NVIDIA drivers across kernel updates."
    read -r -p "Would you like Slacky-Update to automatically download, build and install DKMS from SlackBuilds.org? [Y/n] " reply_dkms
    reply_dkms=${reply_dkms:-Y}
    if [[ "$reply_dkms" =~ ^[YyJjSsOo]$ ]]; then
        validate_privileges
        log_info "Downloading and building DKMS from SlackBuilds.org..."
        local build_dir="/tmp/slacky-dkms-build"
        sudo rm -rf "${build_dir}"
        mkdir -p "${build_dir}"
        (
            cd "${build_dir}"
            curl -sSL "https://slackbuilds.org/slackbuilds/15.0/system/dkms.tar.gz" | tar -xz
            cd dkms
            local dkms_ver
            dkms_ver=$(grep -E '^VERSION=' dkms.SlackBuild | cut -d'"' -f2 || echo "3.0.12")
            curl -sSL -o "dkms-${dkms_ver}.tar.gz" "https://github.com/dell/dkms/archive/v${dkms_ver}/dkms-${dkms_ver}.tar.gz" || curl -sSL -o "dkms-${dkms_ver}.tar.gz" "https://github.com/dell/dkms/archive/refs/tags/v${dkms_ver}.tar.gz"
            sudo bash dkms.SlackBuild
            local pkg_file
            pkg_file=$(ls -t /tmp/dkms-*.t?z 2>/dev/null | head -n1 || true)
            if [ -n "${pkg_file}" ] && [ -f "${pkg_file}" ]; then
                sudo /sbin/upgradepkg --install-new --reinstall "${pkg_file}"
                log_success "DKMS installed successfully!"
            fi
        )
        sudo rm -rf "${build_dir}"
    fi
}

# --- [ SYSTEM CONFIGURATION INTEGRATION ] ---
configure_nvidia_modprobe() {
    validate_privileges
    local conf_file="/etc/modprobe.d/nvidia.conf"

    log_info "Configuring NVIDIA modprobe parameters..."
    sudo mkdir -p /etc/modprobe.d

    cat << 'CONF_EOF' | sudo tee "${conf_file}" >/dev/null
# Generated by slacky-update
blacklist nouveau
options nouveau modeset=0

# Power Management and Video Memory Allocation
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia NVreg_TemporaryFilePath=/var/tmp
CONF_EOF

    log_success "NVIDIA modprobe settings written to: ${conf_file}"
}

# --- [ UPSTREAM VERSION RESOLUTION ] ---
resolve_nvidia_branch_version() {
    local prefix="$1"
    local default_ver="$2"

    curl -sSL -m 8 "https://download.nvidia.com/XFree86/Linux-x86_64/" 2>/dev/null | python3 -c "
import sys, re

html = sys.stdin.read()
if not html:
    print('$default_ver')
    sys.exit(0)

prefix = '$prefix'
matches = re.findall(r'href=[\'\"]?(' + re.escape(prefix) + r'\.[0-9]+(?:\.[0-9]+)?)/?[\'\"]?', html)
if not matches:
    print('$default_ver')
    sys.exit(0)

def parse_v(v):
    return [int(x) for x in v.split('.') if x.isdigit()]

sorted_matches = sorted(list(set(matches)), key=parse_v, reverse=True)
print(sorted_matches[0])
" 2>/dev/null || echo "${default_ver}"
}

get_nvidia_download_url() {
    local branch="$1"
    local ver=""

    case "${branch}" in
        legacy|580)
            ver=$(resolve_nvidia_branch_version "580" "580.95.05")
            ;;
        production|595)
            ver=$(resolve_nvidia_branch_version "595" "595.58.03")
            ;;
        feature|610)
            ver=$(resolve_nvidia_branch_version "610" "610.57.04")
            ;;
        *)
            ver=$(resolve_nvidia_branch_version "595" "595.58.03")
            ;;
    esac

    echo "https://download.nvidia.com/XFree86/Linux-x86_64/${ver}/NVIDIA-Linux-x86_64-${ver}.run"
}

# --- [ DRIVER INSTALLATION ] ---
install_nvidia_run_driver() {
    local branch="$1"
    validate_privileges

    local url
    url=$(get_nvidia_download_url "${branch}")
    local filename
    filename=$(basename "${url}")
    local dest_dir="/var/cache/slacky-update/nvidia"
    local target_file="${dest_dir}/${filename}"

    sudo mkdir -p "${dest_dir}"
    log_info "Downloading NVIDIA driver installer (${branch} branch: ${filename})..."
    sudo curl -sSL -o "${target_file}" "${url}"
    sudo chmod +x "${target_file}"

    configure_nvidia_modprobe

    log_info "Executing NVIDIA driver installer with DKMS..."
    if sudo "${target_file}" --silent --dkms 2>/dev/null || sudo "${target_file}" -s --dkms; then
        log_success "NVIDIA driver installation completed successfully."
    else
        log_warn "NVIDIA installer finished with non-zero exit code. Check /var/log/nvidia-installer.log"
    fi

    build_nvidia_modules "ALL"
    enforce_secure_boot_armor
    register_flatpak_gl_sync
}

# --- [ MULTI-KERNEL MODULE COMPILATION ] ---
build_nvidia_modules() {
    local target_kver="$1"
    validate_privileges

    local dkms_bin
    dkms_bin=$(command -v dkms 2>/dev/null || echo "/usr/sbin/dkms")
    if [ ! -x "${dkms_bin}" ]; then
        log_info "DKMS utility not detected on system."
        if [ "${HAS_NVIDIA}" = "true" ]; then
            log_warn "Tip: Installing DKMS (SlackBuilds.org: system/dkms) enables automated NVIDIA rebuilds on kernel updates."
        fi
        return 0
    fi

    local dkms_status
    dkms_status=$("${dkms_bin}" status 2>/dev/null || true)
    if ! echo "${dkms_status}" | grep -qi "nvidia"; then
        log_info "No registered NVIDIA DKMS module found."
        return 0
    fi

    if [ "${target_kver}" = "ALL" ]; then
        log_info "Rebuilding NVIDIA DKMS modules for all installed kernels..."
        if [ -d "/lib/modules" ]; then
            for kdir in /lib/modules/*; do
                [ -d "${kdir}" ] || continue
                local kver
                kver=$(basename "${kdir}")
                log_info "Building NVIDIA modules for kernel: ${kver}"
                sudo "${dkms_bin}" autoinstall -k "${kver}" || log_warn "DKMS build warning for kernel: ${kver}"
            done
        fi
    else
        log_info "Building NVIDIA DKMS modules for kernel: ${target_kver}..."
        sudo "${dkms_bin}" autoinstall -k "${target_kver}" || log_warn "DKMS build warning for kernel: ${target_kver}"
    fi

    log_success "NVIDIA module compilation phase completed."
}

# --- [ FLATPAK GL SYNCHRONIZATION ] ---
register_flatpak_gl_sync() {
    if command -v flatpak >/dev/null 2>&1; then
        log_info "Synchronizing Flatpak NVIDIA GL runtimes..."
        flatpak update -y --non-interactive >/dev/null 2>&1 || true
        log_success "Flatpak GL synchronization complete."
    fi
}
