#!/usr/bin/env bash
# --- [ NVIDIA DRIVER & DKMS ENGINE ] ---

set -euo pipefail

# --- [ HARDWARE DETECTION & DKMS CHECK ] ---
detect_nvidia_gpu() {
    probe_gpu_hardware
    if [ "${HAS_NVIDIA}" = "false" ]; then
        echo "NONE"
        return 0
    fi

    local pci_devs
    pci_devs=$(lspci -nn 2>/dev/null | grep -iE 'vga|3d|display' | grep -i 'nvidia' || true)

    # Pascal: 10-series (GP100, GP102, GP104, GP106, GP107, GP108) -> Device IDs: 1b00 - 1dff
    if echo "${pci_devs}" | grep -qE '\[10de:(1b[0-9a-f]|1c[0-9a-f]|1d[0-9a-f])\]'; then
        echo "PASCAL"
    # Older than Pascal (Maxwell 900-series: 1300-17ff, Kepler: 0f00-12ff, Fermi/Tesla: 0400-0eff)
    elif echo "${pci_devs}" | grep -qE '\[10de:(0[0-9a-f]{3}|1[0-7][0-9a-f]{2})\]'; then
        echo "LEGACY"
    else
        # Modern: Turing 20-series (1e00-1fff), Ampere 30-series (2200-25ff), Ada 40-series (2600-28ff), Blackwell 50-series (2900+)
        echo "MODERN"
    fi
}

ensure_dkms_installed_interactive() {
    probe_gpu_hardware
    [ "${HAS_NVIDIA}" = "true" ] || return 0

    if command -v dkms >/dev/null 2>&1; then
        return 0
    fi

    echo ""
    log_warn "DKMS utility is not installed on this system."
    echo "DKMS is required to automatically rebuild NVIDIA drivers across kernel updates."
    read -r -p "Would you like Slacky-Update to automatically download, build and install DKMS from SlackBuilds.org? [Y/n] " reply_dkms
    reply_dkms=${reply_dkms:-Y}
    if [[ "$reply_dkms" =~ ^[YyJjSsOo]$ ]]; then
        validate_privileges
        log_info "Downloading and building DKMS from SlackBuilds.org..."
        local build_dir="/tmp/slacky-dkms-build"
        sudo rm -rf "${build_dir}"
        mkdir -p "${build_dir}"
        (
            cd "${build_dir}"
            curl -sSL "https://slackbuilds.org/slackbuilds/15.0/system/dkms.tar.gz" | tar -xz
            cd dkms
            local dkms_ver
            dkms_ver=$(grep -E '^VERSION=' dkms.SlackBuild | cut -d'"' -f2 || echo "3.0.12")
            curl -sSL -o "dkms-${dkms_ver}.tar.gz" "https://github.com/dell/dkms/archive/v${dkms_ver}/dkms-${dkms_ver}.tar.gz" || curl -sSL -o "dkms-${dkms_ver}.tar.gz" "https://github.com/dell/dkms/archive/refs/tags/v${dkms_ver}.tar.gz"
            sudo bash dkms.SlackBuild
            local pkg_file
            pkg_file=$(ls -t /tmp/dkms-*.t?z 2>/dev/null | head -n1 || true)
            if [ -n "${pkg_file}" ] && [ -f "${pkg_file}" ]; then
                sudo "${PKG_UPGRADE_CMD}" --install-new --reinstall "${pkg_file}"
                log_success "DKMS installed successfully!"
            fi
        )
        sudo rm -rf "${build_dir}"
    fi
}

# --- [ SYSTEM CONFIGURATION INTEGRATION ] ---
configure_nvidia_modprobe() {
    validate_privileges
    local conf_file="/etc/modprobe.d/nvidia.conf"

    log_info "Configuring NVIDIA modprobe parameters..."
    sudo mkdir -p /etc/modprobe.d

    cat << 'CONF_EOF' | sudo tee "${conf_file}" >/dev/null
# Generated by slacky-update
blacklist nouveau
options nouveau modeset=0

# Power Management and Video Memory Allocation
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia NVreg_TemporaryFilePath=/var/tmp
CONF_EOF

    log_success "NVIDIA modprobe settings written to: ${conf_file}"
}

# --- [ UPSTREAM VERSION RESOLUTION ] ---
resolve_nvidia_branch_version() {
    local prefix="$1"
    local default_ver="$2"

    curl -sSL -m 8 "https://download.nvidia.com/XFree86/Linux-x86_64/" 2>/dev/null | python3 -c "
import sys, re

html = sys.stdin.read()
if not html:
    print('$default_ver')
    sys.exit(0)

prefix = '$prefix'
matches = re.findall(r'href=[\'\"]?(' + re.escape(prefix) + r'\.[0-9]+(?:\.[0-9]+)?)/?[\'\"]?', html)
if not matches:
    print('$default_ver')
    sys.exit(0)

def parse_v(v):
    return [int(x) for x in v.split('.') if x.isdigit()]

sorted_matches = sorted(list(set(matches)), key=parse_v, reverse=True)
print(sorted_matches[0])
" 2>/dev/null || echo "${default_ver}"
}

get_nvidia_download_url() {
    local branch="$1"
    local ver=""

    case "${branch}" in
        legacy|580)
            ver=$(resolve_nvidia_branch_version "580" "580.95.05")
            ;;
        production|595)
            ver=$(resolve_nvidia_branch_version "595" "595.58.03")
            ;;
        feature|610)
            ver=$(resolve_nvidia_branch_version "610" "610.57.04")
            ;;
        *)
            ver=$(resolve_nvidia_branch_version "595" "595.58.03")
            ;;
    esac

    echo "https://download.nvidia.com/XFree86/Linux-x86_64/${ver}/NVIDIA-Linux-x86_64-${ver}.run"
}

# --- [ DRIVER INSTALLATION ] ---
install_nvidia_run_driver() {
    local branch="$1"
    validate_privileges

    local url
    url=$(get_nvidia_download_url "${branch}")
    local filename
    filename=$(basename "${url}")
    local dest_dir="/var/cache/slacky-update/nvidia"
    local target_file="${dest_dir}/${filename}"

    if [ "$(has_cachyos_kernels_installed 2>/dev/null || echo false)" = "true" ]; then
        local cachy_nv_ver
        cachy_nv_ver=$(detect_cachyos_nvidia_upstream_version)
        local req_ver
        req_ver=$(basename "${filename}" | sed -E 's/NVIDIA-Linux-x86_64-([0-9]+\.[0-9]+(\.[0-9]+)?).*/\1/')
        if [ -n "${cachy_nv_ver}" ] && [ -n "${req_ver}" ]; then
            local is_newer
            is_newer=$(python3 -c "
import sys, re
def p(v): return [int(x) for x in re.sub(r'[^0-9.]', '', v).split('.') if x.isdigit()]
sys.exit(0 if p('$req_ver') > p('$cachy_nv_ver') else 1)
" && echo "true" || echo "false")
            if [ "${is_newer}" = "true" ]; then
                log_warn "WARNING: You have CachyOS kernels installed."
                log_warn "The requested NVIDIA driver (${req_ver}) is newer than CachyOS upstream (${cachy_nv_ver})."
                log_warn "Installing standalone user-space will cause an API mismatch crash on CachyOS kernels!"
                echo ""
                read -r -p "Would you like to cancel and run safe CachyOS-Master synchronization instead? [Y/n] " cancel_choice
                cancel_choice=${cancel_choice:-Y}
                if [[ "$cancel_choice" =~ ^[YyJjSsOo]$ ]]; then
                    log_info "Redirecting to CachyOS-Master synchronization..."
                    ensure_cachyos_nvidia_duties
                    return 0
                fi
            fi
        fi
    fi

    sudo mkdir -p "${dest_dir}" "/var/cache/slacky-update/backup/nvidia"
    log_info "Downloading NVIDIA driver installer (${branch} branch: ${filename})..."
    sudo curl -sSL -o "${target_file}" "${url}"
    sudo chmod +x "${target_file}"
    sudo cp -f "${target_file}" "/var/cache/slacky-update/backup/nvidia/${filename}" 2>/dev/null || true

    configure_nvidia_modprobe

    log_info "Executing NVIDIA driver installer with DKMS..."
    if sudo "${target_file}" --silent --dkms 2>/dev/null || sudo "${target_file}" -s --dkms; then
        log_success "NVIDIA driver installation completed successfully."
    else
        log_warn "NVIDIA installer finished with non-zero exit code. Check /var/log/nvidia-installer.log"
    fi

    build_nvidia_modules "ALL"
    enforce_secure_boot_armor
    register_flatpak_gl_sync "${req_ver:-}"
}

# --- [ MULTI-KERNEL MODULE COMPILATION ] ---
build_nvidia_modules() {
    local target_kver="$1"
    validate_privileges

    local dkms_bin
    dkms_bin=$(command -v dkms 2>/dev/null || echo "/usr/sbin/dkms")
    if [ ! -x "${dkms_bin}" ]; then
        log_info "DKMS utility not detected on system."
        if [ "${HAS_NVIDIA}" = "true" ]; then
            log_warn "Tip: Installing DKMS (SlackBuilds.org: system/dkms) enables automated NVIDIA rebuilds on kernel updates."
        fi
        return 0
    fi

    local dkms_status
    dkms_status=$("${dkms_bin}" status 2>/dev/null || true)
    if ! echo "${dkms_status}" | grep -qi "nvidia"; then
        log_info "No registered NVIDIA DKMS module found."
        return 0
    fi

    local target_ver
    target_ver=$(detect_cachyos_nvidia_upstream_version 2>/dev/null || echo "")
    if [ -z "${target_ver}" ] && [ -f "/sys/module/nvidia/version" ]; then
        target_ver=$(cat /sys/module/nvidia/version 2>/dev/null | tr -d '[:space:]' || echo "")
    fi

    if [ "${target_kver}" = "ALL" ]; then
        log_info "Rebuilding NVIDIA DKMS modules for installed Slackware kernels..."
        if [ -d "/lib/modules" ]; then
            for kdir in /lib/modules/*; do
                [ -d "${kdir}" ] || continue
                local kver
                kver=$(basename "${kdir}")
                [ -f "${kdir}/modules.dep" ] || [ -d "${kdir}/kernel" ] || [ -d "${kdir}/extramodules" ] || continue

                local existing_mod
                existing_mod=$(find -L "${kdir}" -name "nvidia.ko*" 2>/dev/null | head -n 1 || true)
                if [ -n "${existing_mod}" ] && [ -n "${target_ver}" ]; then
                    local cur_v
                    cur_v=$(get_nvidia_module_version "${existing_mod}")
                    if [ "${cur_v}" = "${target_ver}" ]; then
                        log_info "Kernel ${kver} already has matching NVIDIA module (v${cur_v}). Ensuring DKMS registration."
                        register_precompiled_nvidia_in_dkms "${kver}" "${target_ver}"
                        continue
                    fi
                fi

                if [[ "${kver}" =~ -rc ]]; then
                    log_warn "Skipping DKMS build for CachyOS RC kernel (${kver}); RC kernels require precompiled open modules."
                    continue
                fi

                log_info "Building NVIDIA DKMS modules for kernel: ${kver}..."
                sudo "${dkms_bin}" autoinstall -k "${kver}" || log_warn "DKMS build warning for kernel: ${kver}"
            done
        fi
    else
        local existing_mod
        existing_mod=$(find -L "/lib/modules/${target_kver}" "/usr/lib/modules/${target_kver}" -name "nvidia.ko*" 2>/dev/null | head -n 1 || true)
        if [ -n "${existing_mod}" ] && [ -n "${target_ver}" ]; then
            local cur_v
            cur_v=$(get_nvidia_module_version "${existing_mod}")
            if [ "${cur_v}" = "${target_ver}" ]; then
                log_info "Kernel ${target_kver} already has matching NVIDIA module (v${cur_v}). Ensuring DKMS registration."
                register_precompiled_nvidia_in_dkms "${target_kver}" "${target_ver}"
                return 0
            fi
        fi

        if [[ "${target_kver}" =~ -rc ]]; then
            log_warn "Skipping DKMS build for CachyOS RC kernel (${target_kver}); RC kernels require precompiled open modules."
            return 0
        fi

        log_info "Building NVIDIA DKMS modules for kernel: ${target_kver}..."
        sudo "${dkms_bin}" autoinstall -k "${target_kver}" || log_warn "DKMS build warning for kernel: ${target_kver}"
    fi

    log_success "NVIDIA module compilation phase completed."
}

# --- [ FLATPAK GL SYNCHRONIZATION ] ---
register_flatpak_gl_sync() {
    local target_ver="${1:-}"
    if ! command -v flatpak >/dev/null 2>&1; then
        return 0
    fi

    if [ -z "${target_ver}" ]; then
        if [ -f "/sys/module/nvidia/version" ]; then
            target_ver=$(cat /sys/module/nvidia/version 2>/dev/null || true)
        elif command -v nvidia-smi >/dev/null 2>&1; then
            target_ver=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -n 1 || true)
        elif command -v detect_cachyos_nvidia_upstream_version >/dev/null 2>&1; then
            target_ver=$(detect_cachyos_nvidia_upstream_version 2>/dev/null || true)
        fi
    fi

    # Targeted Verification & Synchronization: Check if runtime is needed and missing
    if [ -n "${target_ver}" ]; then
        local ver_clean
        ver_clean=$(echo "${target_ver}" | sed -E 's/^[^0-9]*([0-9]+\.[0-9]+(\.[0-9]+)?).*/\1/')
        if [ -n "${ver_clean}" ]; then
            local ver_dash
            ver_dash=$(echo "${ver_clean}" | tr '.' '-')

            local installed_runtimes
            installed_runtimes=$(flatpak list --runtime --columns=application 2>/dev/null || true)

            local has_32bit_flatpaks="false"
            if echo "${installed_runtimes}" | grep -q "org.freedesktop.Platform.GL32"; then
                has_32bit_flatpaks="true"
            fi

            local pkgs_to_install=()
            if ! echo "${installed_runtimes}" | grep -qE "^org\.freedesktop\.Platform\.GL\.nvidia-${ver_dash}$"; then
                pkgs_to_install+=("org.freedesktop.Platform.GL.nvidia-${ver_dash}")
            fi
            if [ "${has_32bit_flatpaks}" = "true" ]; then
                if ! echo "${installed_runtimes}" | grep -qE "^org\.freedesktop\.Platform\.GL32\.nvidia-${ver_dash}$"; then
                    pkgs_to_install+=("org.freedesktop.Platform.GL32.nvidia-${ver_dash}")
                fi
            fi

            if [ "${#pkgs_to_install[@]}" -gt 0 ]; then
                log_info "Pre-fetching Flatpak NVIDIA GL runtimes for driver ${ver_clean} (nvidia-${ver_dash})..."
                log_info "Downloading Flatpak runtimes in advance: ${pkgs_to_install[*]}"
                flatpak install -y --non-interactive flathub "${pkgs_to_install[@]}" 2>/dev/null || \
                flatpak install -y --non-interactive --system flathub "${pkgs_to_install[@]}" 2>/dev/null || {
                    log_warn "Flatpak runtime pre-fetch from Flathub deferred (runtime may not be published yet; will auto-heal after reboot)."
                }
            else
                log_info "Matching Flatpak NVIDIA GL runtime (nvidia-${ver_dash}) is already installed and verified."
            fi
        fi
    fi
}

# --- [ CACHYOS-MASTER NVIDIA DUALITY & SYNCHRONIZATION ] ---

has_cachyos_kernels_installed() {
    if ls /boot/vmlinuz*cachyos* 1>/dev/null 2>&1 || ls -d /lib/modules/*cachyos* 1>/dev/null 2>&1; then
        echo "true"
    else
        echo "false"
    fi
}
get_cachyos_nvidia_repo_url() {
    local tier="generic"
    if command -v detect_cpu_tier >/dev/null 2>&1; then
        tier=$(detect_cpu_tier)
    fi
    if command -v get_cachyos_repo_url >/dev/null 2>&1; then
        get_cachyos_repo_url "${tier}"
    else
        echo "https://mirror.cachyos.org/repo/x86_64/cachyos/"
    fi
}

detect_cachyos_nvidia_upstream_version() {
    local cachy_repo
    cachy_repo=$(get_cachyos_nvidia_repo_url)
    local ver
    ver=$(curl -sSL -m 10 "${cachy_repo}" 2>/dev/null | grep -o -E 'nvidia-utils-[0-9]+\.[0-9]+(\.[0-9]+)?' | sed 's/nvidia-utils-//' | sort -V | tail -n 1 || echo "")
    echo "${ver}"
}

build_and_deploy_cachyos_nvidia_userspace() {
    local target_ver="$1"

    local cachy_repo
    cachy_repo=$(get_cachyos_nvidia_repo_url)
    local html
    html=$(curl -sSL -m 15 "${cachy_repo}" 2>/dev/null || echo "")
    if [ -z "${html}" ]; then
        log_warn "Could not connect to CachyOS mirror to fetch NVIDIA user-space packages."
        return 1
    fi

    local pkg_utils pkg_lib32 pkg_settings pkg_opencl pkg_lib32_opencl
    pkg_utils=$(echo "${html}" | grep -o -E 'href="nvidia-utils-'${target_ver}'-[^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")
    pkg_lib32=$(echo "${html}" | grep -o -E 'href="lib32-nvidia-utils-'${target_ver}'-[^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")
    pkg_settings=$(echo "${html}" | grep -o -E 'href="nvidia-settings-'${target_ver}'-[^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")
    pkg_opencl=$(echo "${html}" | grep -o -E 'href="opencl-nvidia-'${target_ver}'-[^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")
    pkg_lib32_opencl=$(echo "${html}" | grep -o -E 'href="lib32-opencl-nvidia-'${target_ver}'-[^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")

    # Resolve libva-nvidia-driver (CachyOS mirror or Arch Linux official extra repository)
    local pkg_libva=""
    local libva_url=""
    pkg_libva=$(echo "${html}" | grep -o -E 'href="libva-nvidia-driver-[^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")
    if [ -n "${pkg_libva}" ]; then
        libva_url="${cachy_repo}/${pkg_libva}"
    else
        local arch_extra_repo="https://geo.mirror.pkgbuild.com/extra/os/x86_64"
        local arch_html
        arch_html=$(curl -sSL -m 15 "${arch_extra_repo}/" 2>/dev/null || echo "")
        pkg_libva=$(echo "${arch_html}" | grep -o -E 'href="libva-nvidia-driver-[0-9][^"]*\.pkg\.tar\.zst"' | head -n 1 | cut -d'"' -f2 || echo "")
        if [ -n "${pkg_libva}" ]; then
            libva_url="${arch_extra_repo}/${pkg_libva}"
        fi
    fi

    if [ -z "${pkg_utils}" ]; then
        log_warn "Could not resolve nvidia-utils-${target_ver} from CachyOS repository."
        return 1
    fi

    local staging_base
    staging_base=$(mktemp -d "$(get_user_staging_dir)/cachy-nv-${target_ver}.XXXXXX" 2>/dev/null || mktemp -d /tmp/slacky-cachy-nv.XXXXXX)
    local cache_dir="${staging_base}/downloads"
    local staging_root="${staging_base}/pkg"
    local tmp_extract="${staging_base}/extract"
    trap 'rm -rf "${staging_base:-}" 2>/dev/null || true' INT TERM

    mkdir -p "${cache_dir}" \
             "${staging_root}" \
             "${tmp_extract}/utils" \
             "${tmp_extract}/lib32" \
             "${tmp_extract}/settings" \
             "${tmp_extract}/opencl" \
             "${tmp_extract}/lib32_opencl" \
             "${tmp_extract}/libva"

    log_info "Downloading CachyOS NVIDIA Complete Suite components (${target_ver}) to user staging..."
    local download_list=("${pkg_utils}")
    [ -n "${pkg_lib32}" ] && download_list+=("${pkg_lib32}")
    [ -n "${pkg_settings}" ] && download_list+=("${pkg_settings}")
    [ -n "${pkg_opencl}" ] && download_list+=("${pkg_opencl}")
    [ -n "${pkg_lib32_opencl}" ] && download_list+=("${pkg_lib32_opencl}")

    local dl_items=()
    for pkg_item in "${download_list[@]}"; do
        dl_items+=("${cachy_repo}/${pkg_item}|${cache_dir}/${pkg_item}|${cachy_repo}/${pkg_item}.sig|${cache_dir}/${pkg_item}.sig")
    done
    if [ -n "${pkg_libva}" ] && [ -n "${libva_url}" ]; then
        dl_items+=("${libva_url}|${cache_dir}/${pkg_libva}|${libva_url}.sig|${cache_dir}/${pkg_libva}.sig")
    fi

    if ! download_parallel_pacman "CachyOS NVIDIA Driver Suite (${target_ver})" "${dl_items[@]}"; then
        log_error "Failed to download NVIDIA suite components."
        rm -rf "${staging_base}"
        trap - INT TERM
        return 1
    fi

    for pkg_item in "${download_list[@]}"; do
        if ! verify_cachyos_gpg_signature "${cache_dir}/${pkg_item}" "${cache_dir}/${pkg_item}.sig"; then
            log_error "GPG verification failed for ${pkg_item}! Aborting user-space staging build."
            rm -rf "${staging_base}"
            trap - INT TERM
            return 1
        fi
    done

    if [ -n "${pkg_libva}" ] && [ -n "${libva_url}" ]; then
        if ! verify_cachyos_gpg_signature "${cache_dir}/${pkg_libva}" "${cache_dir}/${pkg_libva}.sig"; then
            log_error "GPG verification failed for ${pkg_libva}! Aborting."
            rm -rf "${staging_base}"
            trap - INT TERM
            return 1
        fi
    fi

    log_info "Unpacking and mapping Complete Suite in user staging..."
    tar --zstd -xf "${cache_dir}/${pkg_utils}" -C "${tmp_extract}/utils" 2>/dev/null || true
    [ -n "${pkg_lib32}" ] && [ -f "${cache_dir}/${pkg_lib32}" ] && tar --zstd -xf "${cache_dir}/${pkg_lib32}" -C "${tmp_extract}/lib32" 2>/dev/null || true
    [ -n "${pkg_settings}" ] && [ -f "${cache_dir}/${pkg_settings}" ] && tar --zstd -xf "${cache_dir}/${pkg_settings}" -C "${tmp_extract}/settings" 2>/dev/null || true
    [ -n "${pkg_opencl}" ] && [ -f "${cache_dir}/${pkg_opencl}" ] && tar --zstd -xf "${cache_dir}/${pkg_opencl}" -C "${tmp_extract}/opencl" 2>/dev/null || true
    [ -n "${pkg_lib32_opencl}" ] && [ -f "${cache_dir}/${pkg_lib32_opencl}" ] && tar --zstd -xf "${cache_dir}/${pkg_lib32_opencl}" -C "${tmp_extract}/lib32_opencl" 2>/dev/null || true
    [ -n "${pkg_libva}" ] && [ -f "${cache_dir}/${pkg_libva}" ] && tar --zstd -xf "${cache_dir}/${pkg_libva}" -C "${tmp_extract}/libva" 2>/dev/null || true

    # Prepare Slackware structure:
    # 64-bit -> /usr/lib64
    # 32-bit -> /usr/lib
    mkdir -p "${staging_root}/usr/bin" \
             "${staging_root}/usr/lib64/dri" \
             "${staging_root}/usr/lib" \
             "${staging_root}/usr/share" \
             "${staging_root}/etc/OpenCL/vendors" \
             "${staging_root}/etc/profile.d" \
             "${staging_root}/lib/firmware/nvidia/${target_ver}" \
             "${staging_root}/install"

    # 1. Map nvidia-utils (64-bit Core)
    if [ -d "${tmp_extract}/utils/usr/bin" ]; then
        cp -a "${tmp_extract}/utils/usr/bin/." "${staging_root}/usr/bin/"
    fi
    if [ -d "${tmp_extract}/utils/usr/share" ]; then
        cp -a "${tmp_extract}/utils/usr/share/." "${staging_root}/usr/share/"
    fi
    if [ -d "${tmp_extract}/utils/etc" ]; then
        cp -a "${tmp_extract}/utils/etc/." "${staging_root}/etc/"
    fi
    if [ -d "${tmp_extract}/utils/usr/lib/firmware/nvidia" ]; then
        cp -a "${tmp_extract}/utils/usr/lib/firmware/nvidia/." "${staging_root}/lib/firmware/nvidia/"
    fi
    if [ -d "${tmp_extract}/utils/usr/lib" ]; then
        (
            cd "${tmp_extract}/utils/usr/lib"
            find . -maxdepth 1 ! -name "." ! -name "environment.d" ! -name "firmware" -exec cp -a {} "${staging_root}/usr/lib64/" \;
        )
    fi

    # 2. Map lib32-nvidia-utils (32-bit multilib Core) -> Slackware /usr/lib
    if [ -d "${tmp_extract}/lib32/usr/lib32" ]; then
        (
            cd "${tmp_extract}/lib32/usr/lib32"
            find . -maxdepth 1 ! -name "." -exec cp -a {} "${staging_root}/usr/lib/" \;
        )
    fi

    # 3. Map nvidia-settings
    if [ -d "${tmp_extract}/settings/usr/bin" ]; then
        cp -a "${tmp_extract}/settings/usr/bin/." "${staging_root}/usr/bin/"
    fi
    if [ -d "${tmp_extract}/settings/usr/share" ]; then
        cp -a "${tmp_extract}/settings/usr/share/." "${staging_root}/usr/share/"
    fi
    if [ -d "${tmp_extract}/settings/usr/lib" ]; then
        cp -a "${tmp_extract}/settings/usr/lib/." "${staging_root}/usr/lib64/"
    fi

    # 4. Map opencl-nvidia (64-bit OpenCL)
    if [ -d "${tmp_extract}/opencl/etc/OpenCL" ]; then
        cp -a "${tmp_extract}/opencl/etc/OpenCL/." "${staging_root}/etc/OpenCL/"
    fi
    if [ -d "${tmp_extract}/opencl/usr/lib" ]; then
        (
            cd "${tmp_extract}/opencl/usr/lib"
            find . -maxdepth 1 ! -name "." -exec cp -a {} "${staging_root}/usr/lib64/" \;
        )
    fi

    # 5. Map lib32-opencl-nvidia (32-bit OpenCL multilib) -> Slackware /usr/lib
    if [ -d "${tmp_extract}/lib32_opencl/usr/lib32" ]; then
        (
            cd "${tmp_extract}/lib32_opencl/usr/lib32"
            find . -maxdepth 1 ! -name "." -exec cp -a {} "${staging_root}/usr/lib/" \;
        )
    fi

    # 6. Map libva-nvidia-driver (VA-API NVDEC driver) -> /usr/lib64/dri/
    if [ -d "${tmp_extract}/libva/usr/lib/dri" ]; then
        cp -a "${tmp_extract}/libva/usr/lib/dri/." "${staging_root}/usr/lib64/dri/"
    fi

    # 7. Hardware video acceleration profile configuration
    cat << 'VA_SH_EOF' > "${staging_root}/etc/profile.d/nvidia-vaapi.sh"
#!/bin/sh
# NVIDIA VA-API hardware video acceleration configuration

# Detect if running on a hybrid laptop where iGPU is primary display
is_hybrid_laptop() {
    [ -d "/sys/class/power_supply" ] && ls /sys/class/power_supply/BAT* >/dev/null 2>&1 || return 1
    local gpus
    gpus=$(lspci -d ::0300 2>/dev/null | wc -l)
    [ "${gpus:-0}" -gt 1 ]
}

if is_hybrid_laptop; then
    # On hybrid laptops, only enable NVIDIA VA-API when PRIME offload is explicitly requested
    if [ "${__NV_PRIME_RENDER_OFFLOAD:-0}" = "1" ] || [ "${DRI_PRIME:-0}" = "1" ]; then
        export LIBVA_DRIVER_NAME=nvidia
        export MOZ_DISABLE_RDD_SANDBOX=1
        export NVD_BACKEND=direct
    fi
else
    # Standard desktop or single-GPU system: enable globally for full HW acceleration
    export LIBVA_DRIVER_NAME=nvidia
    export MOZ_DISABLE_RDD_SANDBOX=1
    export NVD_BACKEND=direct
fi
VA_SH_EOF

    cat << 'VA_CSH_EOF' > "${staging_root}/etc/profile.d/nvidia-vaapi.csh"
#!/bin/csh
# NVIDIA VA-API hardware video acceleration configuration
if ( -d /sys/class/power_supply && `ls /sys/class/power_supply/BAT* >& /dev/null; echo $status` == 0 ) then
    if ( $?__NV_PRIME_RENDER_OFFLOAD || $?DRI_PRIME ) then
        setenv LIBVA_DRIVER_NAME nvidia
        setenv MOZ_DISABLE_RDD_SANDBOX 1
        setenv NVD_BACKEND direct
    endif
else
    setenv LIBVA_DRIVER_NAME nvidia
    setenv MOZ_DISABLE_RDD_SANDBOX 1
    setenv NVD_BACKEND direct
endif
VA_CSH_EOF

    chmod 755 "${staging_root}/etc/profile.d/nvidia-vaapi.sh" "${staging_root}/etc/profile.d/nvidia-vaapi.csh"

    # Clean Arch metadata
    rm -f "${staging_root}/.BUILDINFO" "${staging_root}/.INSTALL" "${staging_root}/.MTREE" "${staging_root}/.PKGINFO"

    # Write Slackware slack-desc
    cat << 'DESC_EOF' > "${staging_root}/install/slack-desc"
cachyos-nvidia-utils: cachyos-nvidia-utils (CachyOS NVIDIA Complete User-Space Suite)
cachyos-nvidia-utils:
cachyos-nvidia-utils: Official NVIDIA graphics libraries (OpenGL, Vulkan, CUDA,
cachyos-nvidia-utils: OpenCL, VA-API NVDEC driver, nvidia-smi, nvidia-settings)
cachyos-nvidia-utils: and 32-bit multilib runtimes (GL, Vulkan, CUDA, OpenCL),
cachyos-nvidia-utils: packaged directly from CachyOS repository for Slackware.
cachyos-nvidia-utils:
cachyos-nvidia-utils: Provides 100% synchronized user-space for CachyOS and
cachyos-nvidia-utils: Slackware kernels to prevent API mismatch.
cachyos-nvidia-utils:
cachyos-nvidia-utils: Maintained by slacky-update.
cachyos-nvidia-utils:
DESC_EOF

    # Write doinst.sh
    cat << 'DOINST_EOF' > "${staging_root}/install/doinst.sh"
if [ -x /sbin/ldconfig ]; then
  /sbin/ldconfig 2>/dev/null || true
fi
if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database /usr/share/applications 2>/dev/null || true
fi
if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true
fi
DOINST_EOF
    chmod 755 "${staging_root}/install/doinst.sh"

    # Enforce standard permissions before packaging
    chmod -R u=rwX,go=rX "${staging_root}"

    log_info "Assembling Slackware txz package: cachyos-nvidia-utils-${target_ver}..."
    local txz_out="${staging_base}/cachyos-nvidia-utils-${target_ver}-x86_64-1_slacky.txz"
    rm -f "${txz_out}"
    (
        cd "${staging_root}"
        "${PKG_MAKE_CMD}" -l y -c n "${txz_out}" >/dev/null 2>&1
    )

    if [ -f "${txz_out}" ]; then
        chmod 644 "${txz_out}"

        # Root stage: Validate privileges and install
        validate_privileges

        # Scan and retire legacy conflicting NVIDIA packages from /var/log/packages to avoid multiple owners
        local legacy_pkgs=("nvidia-driver" "nvidia-kernel" "nvidia-utils" "x11-nvidia-driver")
        for lpkg in "${legacy_pkgs[@]}"; do
            for ppath in /var/log/packages/${lpkg}-[0-9]*; do
                [ -f "${ppath}" ] || continue
                local pbname
                pbname=$(basename "${ppath}")
                log_info "Retiring legacy package database entry: ${pbname}..."
                sudo mkdir -p /var/log/packages/retired_by_slacky
                sudo mv -f "${ppath}" /var/log/packages/retired_by_slacky/ 2>/dev/null || true
                if [ -f "/var/log/scripts/${pbname}" ]; then
                    sudo mkdir -p /var/log/scripts/retired_by_slacky
                    sudo mv -f "/var/log/scripts/${pbname}" /var/log/scripts/retired_by_slacky/ 2>/dev/null || true
                fi
            done
        done

        log_info "Installing cachyos-nvidia-utils package to system..."
        sudo "${PKG_UPGRADE_CMD}" --install-new --reinstall "${txz_out}"
        log_success "CachyOS NVIDIA Complete Suite package deployed: ${target_ver}"
    else
        log_warn "Failed to create cachyos-nvidia-utils txz package."
    fi

    rm -rf "${staging_base}" 2>/dev/null || true
    trap - INT TERM
}

get_nvidia_module_version() {
    local mod="$1"
    [ -f "${mod}" ] || { echo "Unknown"; return 0; }
    local ver=""
    ver=$(modinfo -F version "${mod}" 2>/dev/null || true)
    if [ -z "${ver}" ] || [ "${ver}" = "Unknown" ]; then
        if [[ "${mod}" =~ \.ko\.zst$ ]]; then
            ver=$(unzstd -c "${mod}" 2>/dev/null | strings | grep -E '^version=[0-9]+\.[0-9]+' | cut -d'=' -f2 | head -n 1 || true)
        elif [[ "${mod}" =~ \.ko\.xz$ ]]; then
            ver=$(unxz -c "${mod}" 2>/dev/null | strings | grep -E '^version=[0-9]+\.[0-9]+' | cut -d'=' -f2 | head -n 1 || true)
        elif [[ "${mod}" =~ \.ko\.gz$ ]]; then
            ver=$(gunzip -c "${mod}" 2>/dev/null | strings | grep -E '^version=[0-9]+\.[0-9]+' | cut -d'=' -f2 | head -n 1 || true)
        else
            ver=$(strings "${mod}" 2>/dev/null | grep -E '^version=[0-9]+\.[0-9]+' | cut -d'=' -f2 | head -n 1 || true)
        fi
    fi
    echo "${ver:-Unknown}"
}

register_precompiled_nvidia_in_dkms() {
    local target_kver="$1"
    local target_ver="$2"
    [ -n "${target_kver}" ] || return 0
    [ -n "${target_ver}" ] || return 0

    command -v dkms >/dev/null 2>&1 || return 0

    local mod_dir=""
    if [ -d "/usr/lib/modules/${target_kver}/extramodules" ] && ls "/usr/lib/modules/${target_kver}/extramodules"/nvidia*.ko* >/dev/null 2>&1; then
        mod_dir="/usr/lib/modules/${target_kver}/extramodules"
    elif [ -d "/lib/modules/${target_kver}/extramodules" ] && ls "/lib/modules/${target_kver}/extramodules"/nvidia*.ko* >/dev/null 2>&1; then
        mod_dir="/lib/modules/${target_kver}/extramodules"
    elif [ -d "/usr/lib/modules/${target_kver}/kernel/drivers/video" ] && ls "/usr/lib/modules/${target_kver}/kernel/drivers/video"/nvidia*.ko* >/dev/null 2>&1; then
        mod_dir="/usr/lib/modules/${target_kver}/kernel/drivers/video"
    elif [ -d "/lib/modules/${target_kver}/kernel/drivers/video" ] && ls "/lib/modules/${target_kver}/kernel/drivers/video"/nvidia*.ko* >/dev/null 2>&1; then
        mod_dir="/lib/modules/${target_kver}/kernel/drivers/video"
    fi
    [ -n "${mod_dir}" ] || return 0

    local dkms_target_dir="/var/lib/dkms/nvidia/${target_ver}/${target_kver}/x86_64"
    sudo mkdir -p "${dkms_target_dir}/module" "${dkms_target_dir}/log" 2>/dev/null || true

    for m in "${mod_dir}"/nvidia*.ko*; do
        [ -f "${m}" ] || continue
        local bname
        bname=$(basename "${m}")
        sudo cp -f "${m}" "${dkms_target_dir}/module/${bname}" 2>/dev/null || sudo ln -sf "${m}" "${dkms_target_dir}/module/${bname}" 2>/dev/null || true
    done

    if [ -d "/var/lib/dkms/nvidia" ]; then
        (
            cd /var/lib/dkms/nvidia
            sudo ln -sfn "${target_ver}/${target_kver}/x86_64" "kernel-${target_kver}-x86_64" 2>/dev/null || true
        )
    fi
}

prune_stale_nvidia_modules_for_kernel() {
    local target_kver="$1"
    local target_ver="$2"
    [ -n "${target_kver}" ] || return 0
    [ -n "${target_ver}" ] || return 0

    local pruned_any=0
    local dirs_to_check=()
    [ -d "/lib/modules/${target_kver}" ] && dirs_to_check+=("/lib/modules/${target_kver}")
    [ -d "/usr/lib/modules/${target_kver}" ] && dirs_to_check+=("/usr/lib/modules/${target_kver}")

    for d in "${dirs_to_check[@]}"; do
        while IFS= read -r -d '' mod_file; do
            local mod_ver
            mod_ver=$(get_nvidia_module_version "${mod_file}")
            if [ -n "${mod_ver}" ] && [ "${mod_ver}" != "${target_ver}" ] && [ "${mod_ver}" != "Unknown" ]; then
                log_info "Removing stale NVIDIA module (v${mod_ver} != v${target_ver}): ${mod_file}"
                sudo rm -f "${mod_file}" 2>/dev/null || true
                pruned_any=1
            fi
        done < <(find "${d}" -type f -name "nvidia*.ko*" -print0 2>/dev/null)
    done

    # Remove duplicates if both extramodules/ and kernel/drivers/video/ exist
    for d in "${dirs_to_check[@]}"; do
        if [ -d "${d}/extramodules" ] && ls "${d}/extramodules"/nvidia*.ko* >/dev/null 2>&1; then
            if [ -d "${d}/kernel/drivers/video" ] && ls "${d}/kernel/drivers/video"/nvidia*.ko* >/dev/null 2>&1; then
                local extra_ver kernel_ver
                extra_ver=$(get_nvidia_module_version "$(ls "${d}/extramodules"/nvidia.ko* 2>/dev/null | head -n1)")
                kernel_ver=$(get_nvidia_module_version "$(ls "${d}/kernel/drivers/video"/nvidia.ko* 2>/dev/null | head -n1)")
                if [ "${extra_ver}" = "${target_ver}" ]; then
                    log_info "Retaining precompiled extramodules (v${target_ver}) and removing duplicate DKMS modules for ${target_kver}..."
                    sudo rm -f "${d}/kernel/drivers/video"/nvidia*.ko* 2>/dev/null || true
                    pruned_any=1
                elif [ "${kernel_ver}" = "${target_ver}" ]; then
                    log_info "Retaining DKMS modules (v${target_ver}) and removing duplicate extramodules for ${target_kver}..."
                    sudo rm -f "${d}/extramodules"/nvidia*.ko* 2>/dev/null || true
                    pruned_any=1
                fi
            fi
        fi
    done

    if [ "${pruned_any}" -eq 1 ]; then
        sudo depmod -a "${target_kver}" 2>/dev/null || true
    fi

    register_precompiled_nvidia_in_dkms "${target_kver}" "${target_ver}"
}

sync_stock_kernel_nvidia_module() {
    local stock_kver="$1"
    local cachy_nv_ver="$2"

    [ -n "${stock_kver}" ] || return 0
    [ -n "${cachy_nv_ver}" ] || return 0

    log_info "Synchronizing stock Slackware kernel ${stock_kver} with NVIDIA ${cachy_nv_ver}..."

    # Check if stock kernel already has matching nvidia.ko module version
    local existing_mod
    existing_mod=$(find "/lib/modules/${stock_kver}" "/usr/lib/modules/${stock_kver}" -name "nvidia.ko*" 2>/dev/null | head -n 1 || true)
    if [ -n "${existing_mod}" ]; then
        local cur_mod_ver
        cur_mod_ver=$(get_nvidia_module_version "${existing_mod}")
        if [ "${cur_mod_ver}" = "${cachy_nv_ver}" ]; then
            log_info "Stock kernel ${stock_kver} already has matching NVIDIA module (${cur_mod_ver}). Skipping rebuild."
            return 0
        fi
    fi

    local gpu_arch="MODERN"
    if command -v detect_nvidia_gpu >/dev/null 2>&1; then
        gpu_arch=$(detect_nvidia_gpu)
    fi

    local cachy_repo
    cachy_repo=$(get_cachyos_nvidia_repo_url | sed 's|/*$||')
    local staging_dir
    staging_dir="$(get_user_staging_dir)/dkms"
    mkdir -p "${staging_dir}"

    local dkms_pkg=""
    local dkms_name="nvidia"
    local dkms_ver="${cachy_nv_ver}"

    if [ "${gpu_arch}" = "PASCAL" ]; then
        # Pascal GTX 10-series uses nvidia-580xx-dkms
        local phtml
        phtml=$(curl -sSL --connect-timeout 15 -m 30 "${cachy_repo}/" 2>/dev/null || echo "")
        dkms_pkg=$(echo "${phtml}" | grep -o -E 'nvidia-580xx-dkms-[0-9a-zA-Z_\.-]*\.pkg\.tar\.zst' | head -n 1 || echo "")
        dkms_name="nvidia"
        dkms_ver=$(echo "${dkms_pkg}" | grep -o -E '580\.[0-9]+(\.[0-9]+)?' | head -n 1 || echo "580.178.04")
    else
        # Modern Turing+ RTX series uses nvidia-open-dkms
        local mhtml
        mhtml=$(curl -sSL --connect-timeout 15 -m 30 "${cachy_repo}/" 2>/dev/null || echo "")
        dkms_pkg=$(echo "${mhtml}" | grep -o -E 'nvidia-open-dkms-[0-9a-zA-Z_\.-]*\.pkg\.tar\.zst' | head -n 1 || echo "")
        dkms_name="nvidia"
    fi

    if [ -n "${dkms_pkg}" ]; then
        local dkms_archive="${staging_dir}/${dkms_pkg}"
        local dkms_items=("${cachy_repo}/${dkms_pkg}|${dkms_archive}|${cachy_repo}/${dkms_pkg}.sig|${dkms_archive}.sig")
        if ! download_parallel_pacman "CachyOS NVIDIA DKMS (${dkms_pkg})" "${dkms_items[@]}"; then
            log_error "Failed to download DKMS source package: ${dkms_pkg}"
            rm -rf "${staging_dir}"
            return 1
        fi

        if ! verify_cachyos_gpg_signature "${dkms_archive}" "${dkms_archive}.sig"; then
            log_error "GPG signature verification failed for ${dkms_pkg}! Aborting."
            rm -rf "${staging_dir}"
            return 1
        fi

        if [ -f "${dkms_archive}" ] && [ -s "${dkms_archive}" ]; then
            validate_privileges
            # Unpack /usr/src/nvidia-* to system
            sudo tar --zstd -xf "${dkms_archive}" -C / 2>/dev/null || true

            local dkms_bin
            dkms_bin=$(command -v dkms 2>/dev/null || echo "/usr/sbin/dkms")
            if [ -x "${dkms_bin}" ]; then
                log_info "Compiling NVIDIA module for stock kernel ${stock_kver} via DKMS..."
                sudo "${dkms_bin}" build -m "${dkms_name}" -v "${dkms_ver}" -k "${stock_kver}" 2>/dev/null || log_warn "DKMS build warning for ${stock_kver}"
                sudo "${dkms_bin}" install -m "${dkms_name}" -v "${dkms_ver}" -k "${stock_kver}" 2>/dev/null || log_warn "DKMS install warning for ${stock_kver}"
                log_success "NVIDIA kernel module built for stock kernel: ${stock_kver}"
            fi
        fi
    fi

    validate_privileges
    sudo "${DEPMOD_CMD}" -a "${stock_kver}" 2>/dev/null || true
    if command -v generate_kernel_initramfs >/dev/null 2>&1; then
        generate_kernel_initramfs "${stock_kver}"
    fi
}

rollback_cachyos_to_slackware_nvidia() {
    validate_privileges
    [ "${HAS_NVIDIA}" = "true" ] || return 0

    log_info "Initiating rollback from CachyOS NVIDIA Suite to official Slackware standalone driver..."

    # 1. Clean up CachyOS NVIDIA user-space package from /var/log/packages
    for pkg in /var/log/packages/cachyos-nvidia-utils-*; do
        [ -f "${pkg}" ] || continue
        local pbase
        pbase=$(basename "${pkg}")
        log_info "Removing CachyOS package: ${pbase}..."
        sudo "${PKG_REMOVE_CMD}" "${pbase}" 2>/dev/null || true
    done

    # 2. Determine appropriate branch (Pascal -> legacy/580, Modern -> production/595)
    local gpu_arch="MODERN"
    if command -v detect_nvidia_gpu >/dev/null 2>&1; then
        gpu_arch=$(detect_nvidia_gpu)
    fi

    local target_branch="production"
    if [ "${gpu_arch}" = "PASCAL" ]; then
        target_branch="legacy"
    fi

    log_info "Installing official NVIDIA .run driver (${target_branch} branch) with DKMS..."
    install_nvidia_run_driver "${target_branch}"
    log_success "Rollback to official Slackware NVIDIA driver completed!"
}

sync_all_stock_kernels_nvidia() {
    local cachy_nv_ver="$1"
    [ -n "${cachy_nv_ver}" ] || return 0

    if [ -d "/lib/modules" ]; then
        for kdir in /lib/modules/*; do
            [ -d "${kdir}" ] || continue
            local kver
            kver=$(basename "${kdir}")
            # Skip CachyOS kernels as they receive cachyos-*-nvidia-open
            [[ "${kver}" =~ cachyos ]] && continue
            if [ -d "${kdir}/build" ] || [ -d "/usr/src/linux-${kver}" ]; then
                sync_stock_kernel_nvidia_module "${kver}" "${cachy_nv_ver}"
            fi
        done
    fi
}

ensure_cachyos_nvidia_dkms_source_unpacked() {
    local cachy_nv_ver="$1"
    local gpu_arch="${2:-MODERN}"
    local cachy_repo
    cachy_repo=$(get_cachyos_nvidia_repo_url | sed 's|/*$||')
    local staging_dir
    staging_dir="$(get_user_staging_dir)/dkms"
    mkdir -p "${staging_dir}"

    local dkms_pkg=""
    local dkms_name="nvidia"
    local dkms_ver="${cachy_nv_ver}"

    if [ "${gpu_arch}" = "PASCAL" ]; then
        local phtml
        phtml=$(curl -sSL --connect-timeout 15 -m 30 "${cachy_repo}/" 2>/dev/null || echo "")
        dkms_pkg=$(echo "${phtml}" | grep -o -E 'nvidia-580xx-dkms-[0-9a-zA-Z_\.-]*\.pkg\.tar\.zst' | head -n 1 || echo "")
        dkms_name="nvidia"
        dkms_ver=$(echo "${dkms_pkg}" | grep -o -E '580\.[0-9]+(\.[0-9]+)?' | head -n 1 || echo "580.178.04")
    else
        local mhtml
        mhtml=$(curl -sSL --connect-timeout 15 -m 30 "${cachy_repo}/" 2>/dev/null || echo "")
        dkms_pkg=$(echo "${mhtml}" | grep -o -E 'nvidia-open-dkms-[0-9a-zA-Z_\.-]*\.pkg\.tar\.zst' | head -n 1 || echo "")
        dkms_name="nvidia"
    fi

    if [ -n "${dkms_pkg}" ]; then
        local dkms_archive="${staging_dir}/${dkms_pkg}"
        local dkms_items=("${cachy_repo}/${dkms_pkg}|${dkms_archive}|${cachy_repo}/${dkms_pkg}.sig|${dkms_archive}.sig")
        if download_parallel_pacman "CachyOS NVIDIA DKMS (${dkms_pkg})" "${dkms_items[@]}" 2>/dev/null; then
            if verify_cachyos_gpg_signature "${dkms_archive}" "${dkms_archive}.sig" 2>/dev/null; then
                validate_privileges
                sudo tar --zstd -xf "${dkms_archive}" -C / 2>/dev/null || true
            fi
        fi
    fi
    echo "${dkms_name}|${dkms_ver}"
}

sync_all_cachyos_kernels_nvidia() {
    local cachy_nv_ver="$1"
    [ -n "${cachy_nv_ver}" ] || return 0

    local gpu_arch="MODERN"
    if command -v detect_nvidia_gpu >/dev/null 2>&1; then
        gpu_arch=$(detect_nvidia_gpu)
    fi
    [ "${gpu_arch}" = "LEGACY" ] && return 0

    local cachy_repo
    cachy_repo=$(get_cachyos_nvidia_repo_url | sed 's|/*$||')
    local html
    html=$(curl -sSL -m 15 "${cachy_repo}/" 2>/dev/null || echo "")
    [ -n "${html}" ] || return 0

    local search_dirs=()
    [ -d "/usr/lib/modules" ] && search_dirs+=("/usr/lib/modules")
    [ -d "/lib/modules" ] && search_dirs+=("/lib/modules")

    local processed_kvers=()
    for mod_parent in "${search_dirs[@]}"; do
        for kdir in "${mod_parent}"/*; do
            [ -d "${kdir}" ] || continue
            local kver
            kver=$(basename "${kdir}")
            [[ "${kver}" =~ cachyos ]] || continue

            # Prevent processing the same kernel version twice
            if [[ " ${processed_kvers[*]:-} " =~ [[:space:]]${kver}[[:space:]] ]]; then
                continue
            fi
            processed_kvers+=("${kver}")

            local existing_mod
            existing_mod=$(find -L "${kdir}" -name "nvidia.ko*" 2>/dev/null | head -n 1 || true)
            local cur_mod_ver="None"
            [ -n "${existing_mod}" ] && cur_mod_ver=$(get_nvidia_module_version "${existing_mod}")

            if [ "${cur_mod_ver}" != "${cachy_nv_ver}" ]; then
                log_info "Synchronizing CachyOS kernel ${kver} NVIDIA module (${cur_mod_ver} -> ${cachy_nv_ver})..."
                if [ "${gpu_arch}" = "MODERN" ]; then
                    local pref="linux-cachyos"
                    if [[ "${kver}" =~ -bore-lto ]]; then
                        pref="linux-cachyos-bore-lto"
                    elif [[ "${kver}" =~ -rt-bore ]]; then
                        pref="linux-cachyos-rt-bore"
                    elif [[ "${kver}" =~ -bore ]]; then
                        pref="linux-cachyos-bore"
                    elif [[ "${kver}" =~ -eevdf ]]; then
                        pref="linux-cachyos-eevdf"
                    elif [[ "${kver}" =~ -bmq ]]; then
                        pref="linux-cachyos-bmq"
                    elif [[ "${kver}" =~ -deckify ]]; then
                        pref="linux-cachyos-deckify"
                    elif [[ "${kver}" =~ -rc ]]; then
                        pref="linux-cachyos-rc"
                    elif [[ "${kver}" =~ -lts ]]; then
                        pref="linux-cachyos-lts"
                    fi

                    # 1. Primary Fast-Path: Precompiled CachyOS binary module
                    local pkg_pattern="${pref}-nvidia-open-[0-9a-zA-Z_\.-]*\.pkg\.tar\.zst"
                    local matched_pkg=""
                    local candidate_pkgs
                    candidate_pkgs=$(echo "${html}" | grep -o -E "${pkg_pattern}" || echo "")
                    local kver_clean
                    kver_clean=$(echo "${kver}" | sed -E 's/-cachyos.*$//')
                    for c_pkg in ${candidate_pkgs}; do
                        if echo "${c_pkg}" | grep -q "${kver_clean}"; then
                            matched_pkg="${c_pkg}"
                            break
                        elif [[ "${kver}" =~ -rc ]] && [[ "${c_pkg}" =~ -rc ]]; then
                            local k_rc p_rc
                            k_rc=$(echo "${kver}" | grep -o -E 'rc[0-9]+' || echo "")
                            p_rc=$(echo "${c_pkg}" | grep -o -E 'rc[0-9]+' || echo "")
                            if [ -n "${k_rc}" ] && [ "${k_rc}" = "${p_rc}" ]; then
                                matched_pkg="${c_pkg}"
                                break
                            fi
                        fi
                    done

                    local deployed_precompiled=0
                    if [ -n "${matched_pkg}" ]; then
                        local staging_dir
                        staging_dir="$(get_user_staging_dir)/cachy-nv-modules"
                        mkdir -p "${staging_dir}"
                        local nv_file="${staging_dir}/${matched_pkg}"
                        local nv_items=("${cachy_repo}/${matched_pkg}|${nv_file}|${cachy_repo}/${matched_pkg}.sig|${nv_file}.sig")
                        if download_parallel_pacman "CachyOS NVIDIA Module (${kver})" "${nv_items[@]}" && verify_cachyos_gpg_signature "${nv_file}" "${nv_file}.sig"; then
                            validate_privileges
                            log_info "Deploying precompiled NVIDIA open driver to kernel ${kver}..."
                            sudo tar --zstd -xf "${nv_file}" -C /
                            prune_stale_nvidia_modules_for_kernel "${kver}" "${cachy_nv_ver}"
                            if command -v generate_kernel_initramfs >/dev/null 2>&1; then
                                generate_kernel_initramfs "${kver}"
                            fi
                            deployed_precompiled=1
                        fi
                    fi

                    # 2. Secondary Hybrid Fallback: DKMS Bridge for older/intermediate CachyOS kernels (non-RC only)
                    if [ "${deployed_precompiled}" -eq 0 ]; then
                        if [[ "${kver}" =~ -rc ]]; then
                            log_warn "Notice: CachyOS RC kernel (${kver}) requires precompiled open module; skipping DKMS fallback."
                        elif command -v dkms >/dev/null 2>&1 && ([ -d "/lib/modules/${kver}/build" ] || [ -d "/usr/src/linux-headers-${kver}" ]); then
                            log_info "No precompiled module matching ${kver} found on mirrors. Engaging DKMS Bridge..."
                            ensure_cachyos_nvidia_dkms_source_unpacked "${cachy_nv_ver}" "MODERN" >/dev/null 2>&1 || true
                            validate_privileges
                            log_info "Building nvidia-open ${cachy_nv_ver} for CachyOS kernel ${kver} via DKMS..."
                            if sudo dkms build -m nvidia -v "${cachy_nv_ver}" -k "${kver}" 2>/dev/null; then
                                sudo dkms install -m nvidia -v "${cachy_nv_ver}" -k "${kver}" 2>/dev/null || log_warn "DKMS install warning for ${kver}"
                                prune_stale_nvidia_modules_for_kernel "${kver}" "${cachy_nv_ver}"
                                if command -v generate_kernel_initramfs >/dev/null 2>&1; then
                                    generate_kernel_initramfs "${kver}"
                                fi
                            else
                                log_warn "DKMS build was unsuccessful for kernel: ${kver} (skipping install)"
                            fi
                        else
                            log_warn "Could not resolve precompiled module or DKMS toolchain for CachyOS kernel ${kver}."
                        fi
                    fi
                elif [ "${gpu_arch}" = "PASCAL" ]; then
                    if command -v dkms >/dev/null 2>&1; then
                        validate_privileges
                        ensure_cachyos_nvidia_dkms_source_unpacked "${cachy_nv_ver}" "PASCAL" >/dev/null 2>&1 || true
                        local dkms_ver
                        dkms_ver=$(dkms status 2>/dev/null | grep -E '^nvidia/' | awk -F'[,/]' '{print $2}' | tr -d ' ' | head -n 1 || echo "580.178.04")
                        log_info "Building nvidia ${dkms_ver} for CachyOS kernel ${kver} via DKMS..."
                        sudo dkms build -m nvidia -v "${dkms_ver}" -k "${kver}" 2>/dev/null || true
                        sudo dkms install -m nvidia -v "${dkms_ver}" -k "${kver}" 2>/dev/null || true
                        prune_stale_nvidia_modules_for_kernel "${kver}" "${cachy_nv_ver}"
                        if command -v generate_kernel_initramfs >/dev/null 2>&1; then
                            generate_kernel_initramfs "${kver}"
                        fi
                    fi
                fi
            else
                # Module is already matching; ensure no duplicate stale modules linger in extramodules/ or drivers/video
                prune_stale_nvidia_modules_for_kernel "${kver}" "${cachy_nv_ver}"
            fi
        done
    done
}

ensure_cachyos_nvidia_duties() {
    probe_gpu_hardware
    [ "${HAS_NVIDIA}" = "true" ] || return 0

    local has_cachy
    has_cachy=$(has_cachyos_kernels_installed)
    [ "${has_cachy}" = "true" ] || return 0

    # Clean up obsolete kernels (including older RC kernels where only the latest is kept)
    if command -v purge_old_cachyos_kernels >/dev/null 2>&1; then
        purge_old_cachyos_kernels --no-sync
    fi

    local cachy_nv_ver
    cachy_nv_ver=$(detect_cachyos_nvidia_upstream_version)
    if [ -z "${cachy_nv_ver}" ]; then
        log_warn "Unable to detect CachyOS NVIDIA upstream version."
        return 0
    fi

    # Prune any stale competing modules across all installed kernel directories
    if [ -d "/lib/modules" ]; then
        for kdir in /lib/modules/*; do
            [ -d "${kdir}" ] || continue
            local kver
            kver=$(basename "${kdir}")
            prune_stale_nvidia_modules_for_kernel "${kver}" "${cachy_nv_ver}"
        done
    fi

    local pending_rebuilds=0
    local status_lines=()
    if [ -d "/lib/modules" ]; then
        for kdir in /lib/modules/*; do
            [ -d "${kdir}" ] || continue
            local kver
            kver=$(basename "${kdir}")
            [ -f "${kdir}/modules.dep" ] || [ -d "${kdir}/kernel" ] || [ -d "${kdir}/extramodules" ] || continue
            local k_mod
            k_mod=$(find -L "${kdir}" -name "nvidia.ko*" 2>/dev/null | head -n 1 || true)
            if [ -n "${k_mod}" ]; then
                local k_ver
                k_ver=$(get_nvidia_module_version "${k_mod}")
                if [ "${k_ver}" = "${cachy_nv_ver}" ]; then
                    status_lines+=(" • Kernel ${kver}: nvidia.ko ${GREEN}${k_ver} [Matched ✓]${RESET}")
                else
                    status_lines+=(" • Kernel ${kver}: nvidia.ko ${YELLOW}${k_ver} [Rebuild pending -> ${cachy_nv_ver}]${RESET}")
                    pending_rebuilds=$((pending_rebuilds + 1))
                fi
            else
                status_lines+=(" • Kernel ${kver}: nvidia.ko ${YELLOW}None [Rebuild pending -> ${cachy_nv_ver}]${RESET}")
                pending_rebuilds=$((pending_rebuilds + 1))
            fi
        done
    fi

    # 1. Verify or deploy CachyOS user-space package
    local installed_pkg
    installed_pkg=$(ls /var/log/packages/cachyos-nvidia-utils-* 2>/dev/null | head -n 1 || true)
    local need_userspace="false"
    if [ -z "${installed_pkg}" ]; then
        need_userspace="true"
    else
        local cur_pkg_ver
        cur_pkg_ver=$(basename "${installed_pkg}" | sed -E 's/cachyos-nvidia-utils-([0-9]+\.[0-9]+(\.[0-9]+)?).*/\1/')
        if [ "${cur_pkg_ver}" != "${cachy_nv_ver}" ]; then
            need_userspace="true"
        elif [ ! -f "/etc/OpenCL/vendors/nvidia.icd" ] || [ ! -f "/usr/lib64/dri/nvidia_drv_video.so" ]; then
            log_info "Detected legacy CachyOS userspace missing OpenCL or VA-API driver. Migrating to Complete Suite..."
            need_userspace="true"
        fi
    fi

    if [ "${pending_rebuilds}" -gt 0 ] || [ "${need_userspace}" = "true" ] || [ "${INTERACTIVE_NVIDIA:-0}" = "1" ]; then
        log_info "CachyOS-Master NVIDIA mode active. Target driver version: ${cachy_nv_ver}"
        echo ""
        echo -e "${CYAN}${BOLD}=== [ CachyOS-Master Pre-Flight Status ] ===${RESET}"
        echo -e " • Target Driver Suite: ${GREEN}${cachy_nv_ver}${RESET} (64-bit + 32-bit Multilib + OpenCL + VA-API + Settings)"
        for sl in "${status_lines[@]}"; do
            echo -e "${sl}"
        done
        echo -e "${CYAN}============================================${RESET}"
        echo ""
    fi

    if [ "${need_userspace}" = "true" ]; then
        build_and_deploy_cachyos_nvidia_userspace "${cachy_nv_ver}"
    else
        log_info "CachyOS NVIDIA Complete Suite is up to date: ${cachy_nv_ver}"
    fi

    # 2. Synchronize installed CachyOS and stock kernels if pending rebuilds exist
    if [ "${pending_rebuilds}" -gt 0 ]; then
        sync_all_cachyos_kernels_nvidia "${cachy_nv_ver}"
        sync_all_stock_kernels_nvidia "${cachy_nv_ver}"
    fi

    # Check if any installed kernel is missing its initramfs image OR has a stale initramfs older than its nvidia.ko
    local engine
    engine=$(detect_initramfs_engine 2>/dev/null || echo "mkinitrd")
    local missing_kvers=()
    if [ -d "/lib/modules" ]; then
        for kdir in /lib/modules/*; do
            [ -d "${kdir}" ] || continue
            local kver
            kver=$(basename "${kdir}")
            [ -f "${kdir}/modules.dep" ] || continue
            if ! sudo test -f "/boot/vmlinuz-${kver}" && ! sudo test -f "/boot/vmlinuz-generic" && ! sudo test -f "/boot/vmlinuz" && ! sudo ls /boot/vmlinuz*"${kver}"* >/dev/null 2>&1; then
                continue
            fi

            local k_mod
            k_mod=$(find -L "${kdir}" -name "nvidia.ko*" 2>/dev/null | head -n 1 || true)

            if [ "${engine}" = "dracut" ]; then
                local img="/boot/initramfs-${kver}.img"
                if ! sudo test -f "${img}"; then
                    missing_kvers+=("${kver}")
                elif [ -n "${k_mod}" ] && [ -f "${k_mod}" ] && sudo test "${k_mod}" -nt "${img}"; then
                    log_info "Detected initramfs for kernel ${kver} is older than its updated NVIDIA module. Rebuilding..."
                    missing_kvers+=("${kver}")
                fi
            else
                local img="/boot/initrd-${kver}.gz"
                sudo test -f "${img}" || img="/boot/initrd-${kver}.img"
                sudo test -f "${img}" || img="/boot/initrd.gz"
                if ! sudo test -f "${img}"; then
                    missing_kvers+=("${kver}")
                elif [ -n "${k_mod}" ] && [ -f "${k_mod}" ] && sudo test "${k_mod}" -nt "${img}"; then
                    log_info "Detected initrd for kernel ${kver} is older than its updated NVIDIA module. Rebuilding..."
                    missing_kvers+=("${kver}")
                fi
            fi
        done
    fi

    # 3. Secure Boot, Initramfs & Bootloader synchronization (Targeted or Full, unless deferred)
    if [ "${DEFER_BOOT_SYNC:-0}" != "1" ]; then
        if [ "${need_userspace}" = "true" ]; then
            configure_nvidia_modprobe
            log_info "Regenerating ${engine} initramfs images for all installed kernels with updated NVIDIA driver (${cachy_nv_ver})..."
            if command -v generate_kernel_initramfs >/dev/null 2>&1; then
                generate_kernel_initramfs "ALL"
            fi
        elif [ "${#missing_kvers[@]}" -gt 0 ]; then
            configure_nvidia_modprobe
            for mk in "${missing_kvers[@]}"; do
                log_info "Generating missing ${engine} initramfs for kernel: ${mk}..."
                if command -v generate_kernel_initramfs >/dev/null 2>&1; then
                    generate_kernel_initramfs "${mk}"
                fi
            done
        fi

        if [ "${pending_rebuilds}" -gt 0 ] || [ "${need_userspace}" = "true" ] || [ "${#missing_kvers[@]}" -gt 0 ]; then
            if command -v purge_old_slackware_kernels >/dev/null 2>&1; then
                purge_old_slackware_kernels --no-sync
            fi
            if command -v purge_old_cachyos_kernels >/dev/null 2>&1; then
                purge_old_cachyos_kernels --no-sync
            fi

            if command -v enforce_secure_boot_armor >/dev/null 2>&1; then
                enforce_secure_boot_armor
            fi

            log_info "Synchronizing bootloader configurations (GRUB / Limine)..."
            if command -v sync_bootloader_configuration >/dev/null 2>&1; then
                sync_bootloader_configuration "$(uname -r)"
            fi

            register_flatpak_gl_sync "${cachy_nv_ver}"
            log_success "CachyOS-Master NVIDIA Full Suite synchronization completed!"
        else
            log_success "All CachyOS and stock kernel NVIDIA modules (v${cachy_nv_ver}) are matched and up to date."
        fi
    else
        log_success "All CachyOS and stock kernel NVIDIA modules (v${cachy_nv_ver}) are matched and up to date (boot sync deferred)."
    fi
}

